### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by Rahmeesha26** [sei-ec-remote/project-1-issues#159]
### What's the problem you're trying to solve?

1. moving the words on top the start page
2. drawing using <canvas> idk what I'm doing wrong.

### Post any code you think might be relevant (one fenced block per file)
```css
h1 {
    color: crimson;
    text-align: center;
    padding-top: 50px;
}

button {
    margin: 20px 0px 0px 300px;
    width: 60px;
}

.gg {
    background-color: black;
    color: white;
    margin-top: 5px;
}

canvas {
    border: 2px solid crimson;
    display: contents;
}

.start {
    width: 500px;
    height: 500px;
}
```

```js
function drawImage() {
    const canvas = document.getElementById('horror')
    const ctx = document.getContext('2d');
    const img = new Image();
    
    ctx.drawImage(img, 0, 0, 50, 50);
}   

function copyImageToCanvas() {
    const img = document.querySelector('img');
    const canvas = document.querySelector('canvas');

    const ctx = canvas.getContext('2d');

    ctx.drawImage(img, 0, 0, 50, 20, 30, 30, 32, 32);

}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I don't see the behavior I thought I'm suppose to see

### What is your best guess as to the source of the problem?
I'm thinking maybe do a few google searches to see what I can do, I'm not entirely sure. 

### Paste a link to your repository here
https://github.com/Rahmeesha26/Days-End
