### ISSUE TITLE
Justify-self behaving unexpectedly.

### ISSUE THREAD

**Issue by cooperwhitley** [sei-ec-remote/project-1-issues#166]
### What's the problem you're trying to solve?

A progress bar is not following my `justify-self:` css property assigned to its class, 

### Post any code you think might be relevant (one fenced block per file)
html for item:
```html
<progress id="enemy-healthbar" class="enemy-infobox healthbar infobox"></progress>
```
css for item:
```css
.enemy-infobox {
    grid-area: 1 / 7 / 3 / 11;
    z-index: 3;
}
.healthbar {
    border: none;
    width: 225px;
    z-index: 4;
    align-self: center;
    justify-self: center;
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

![bad-justification](https://github.com/sei-ec-remote/project-1-issues/assets/139016429/d6ddf5ff-0b0d-40b1-8864-0b9707a48a01)

This image shows the grid and location of the problematic element. Given what I have the `justify-self` css property set to I would expect for the health bars to be located in the center of their grid areas. Note that `align-self` is behaving as expected.

### What is your best guess as to the source of the problem?

Probably something I'm missing with the configuration and default behavior of `justify-self`

### What things have you already tried to solve the problem?

Swapping `justify-self` to be specific to the ids of the individual progress bars yielded the same result

### Paste a link to your repository here

https://github.com/cooperwhitley/morpheusmelee
