### ISSUE TITLE
Play Again Button not working properly

### ISSUE THREAD

**Issue by jpineda48** [sei-ec-remote/project-1-issues#185]
### What's the problem you're trying to solve?

my init function isn't working properly. its not clearing entire board properly and just appending t9o existing board. 

### Post any code you think might be relevant (one fenced block per file)
```js
  
     ///card options array
const cardArray = [
    {name: '1', img: 'images/1.png'},
    {name: '1', img: 'images/1.png'},
    {name: '2', img: 'images/2.png'},
    {name: '2', img: 'images/2.png'},
    {name: '3', img: 'images/3.png'},
    {name: '3', img: 'images/3.png'},
    {name: '4', img: 'images/4.png'},
    {name: '4', img: 'images/4.png'},
    {name: '5', img: 'images/5.png'},
    {name: '5', img: 'images/5.png'},
    {name: '6', img: 'images/6.png'},
    {name: '6', img: 'images/6.png'}
]


const grid = document.querySelector('.grid')
const resultDisplay = document.querySelector('.score')
const playAgain = document.querySelector('button')
const cardsWon = []
let cardsChosen =[]
let cardsChosenId = []




function init (){
const cardArray = [
    {name: '1', img: 'images/1.png'},
    {name: '1', img: 'images/1.png'},
    {name: '2', img: 'images/2.png'},
    {name: '2', img: 'images/2.png'},
    {name: '3', img: 'images/3.png'},
    {name: '3', img: 'images/3.png'},
    {name: '4', img: 'images/4.png'},
    {name: '4', img: 'images/4.png'},
    {name: '5', img: 'images/5.png'},
    {name: '5', img: 'images/5.png'},
    {name: '6', img: 'images/6.png'},
    {name: '6', img: 'images/6.png'}
]


render()


}


function renderBoard() {
cardArray.sort(function(){return 0.5 - Math.random()});
for(let i =0; i<cardArray.length; i++){
    const card = document.createElement('img')
    card.setAttribute('src', 'images/StartPhoto.png')
    card.setAttribute('data-id', i)
    card.addEventListener('click', showCard)
    grid.append(card)


}
}


function startGame (){
const startBtn = document.querySelector('.start');
startBtn.addEventListener('click', function(){
const text = document.querySelectorAll('div h3');
    for(var i=0; i<text.length; i++) {
    text[i].parentNode.removeChild(text[i]);
    }
    const button = document.querySelector('.start')
    button.remove()
    timer()
   })
   
}

function timer() {
const timeH = document.querySelector('.timer')
let timeSecond = 5;
timeH.innerHTML = `Seconds Left: ${timeSecond}`
const countDown = setInterval(()=> {
    timeSecond--;
    timeH.innerHTML = `Seconds Left: ${timeSecond}`;
if(timeSecond <= 0 || timeSecond < 1){
    resultDisplay.textContent = "You Lost!"
    playAgain.style.visibility ='visible'
    clearInterval(countDown);
}
   if(cardsWon.length === cardArray.length/2) {
    clearInterval(countDown);
    playAgain.style.visibility ='visible'
}
return
},1000)
}



function checkForMatch () {
let cards = document.querySelectorAll('img')
const firstChoice = cardsChosenId[0]
const secondChoice = cardsChosenId[1]
if (cardsChosen[0]=== cardsChosen[1]){
    cards[firstChoice].setAttribute('src', `images/${cardArray[firstChoice].name}.png`)
    cards[firstChoice].removeEventListener("click", showCard)

    cards[secondChoice].setAttribute('src', `images/${cardArray[secondChoice].name}.png`)
    cards[secondChoice].removeEventListener("click", showCard)
    cardsWon.push(cardsChosen)
    }else {
        cards[firstChoice].setAttribute('src', 'images/coverPhoto.png')
        cards[secondChoice].setAttribute('src', 'images/coverPhoto.png')
     }
     cardsChosen = []
     cardsChosenId = []
     resultDisplay.textContent = `Score ${cardsWon.length}`
     if(cardsWon.length === cardArray.length/2) {
        resultDisplay.textContent = 'CONGRATS YOU WON'
      }
}





function showCard (){
let cardId = this.getAttribute('data-id')
cardsChosen.push(cardArray[cardId].name)
cardsChosenId.push(cardId)
this.setAttribute('src', cardArray[cardId].img)
if (cardsChosen.length === 2) {
    setTimeout(checkForMatch, 500)
}
}



function render() {
    renderBoard()
    startGame ()
    checkForMatch ()
    
}





playAgain.addEventListener('click', init)
init()




```
```css
* {
    box-sizing: border-box;
   
}
 
body {
    margin-top:50px;
    margin-bottom: 50px;
    padding:0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    flex-direction: column;
    background-color: rgb(242, 235, 211);
}
.grid {
    width: 620px;
    margin-top: 0;
    margin-bottom: 20px;
    height: 100vh;
    background-color: rgb(242, 235, 211);
    border: 20px white solid;
    border-radius: 8%;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
    align-items: center;
    position: relative;
    gap: 20px;

}
div img {
    width: 130px;
    height: 200px;
    background-color: white;
    border:solid 2px black;
    box-sizing: border-box;
    display: flex;
    justify-content: space-between;
    align-items: center;

}
button {
  position: absolute;
  top: 87%;
  left: 50%;
  transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  background-color: rgb(228,49,34);
  color: white;
  font-size: 16px;
  padding: 62px 84px;
  cursor: pointer;
  border-bottom: 30px solid black;
  border-left: 25px solid rgb(242, 235, 211);
  border-right: 25px solid rgb(242, 235, 211);
  height: 0;
  width: 100px;
  margin: 0 auto;
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 50px;
  font-family: 'Belanosima', sans-serif;
  
}

.heading {
  position: absolute;
  color: rgb(228,49,34);;
  z-index: 1;
  top: 10%;
  width: 100%;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  font-size: 40px;
  text-shadow: 3px 0 0 #000, 0 1px 0 #000, 0 1px 0 #000, -1px 0 0 #000;
  font-family: 'Belanosima', sans-serif;
  letter-spacing: .2rem;

}
.title {
    font-size: 100px;

}
.sub {
    display: flex;
    color: black;
    background-color: white;
    background: rgba(255,255,255, 0.9);
    justify-content: center;
    align-items: center;
    font-family: 'Belleza', sans-serif;
    text-align: center;
    text-shadow: none;
    margin-top: 0;
    line-height: 2;
    letter-spacing: .2rem;
}
.score {
 font-size: 40px;
 margin-bottom: 0;
 
}
.timer {

    margin:0;
    font-size: 40px;
}
.end {
    visibility: hidden;
    position: absolute;
    margin-top: 30%;
    top: 40%;
    left: 50%;
    transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    background-color: black;
    border-left: 25px solid black;
    border-right: 25px solid black;
}

```

### What is your best guess as to the source of the problem?

i cant clear the board

### What things have you already tried to solve the problem?

i think ive tried everything. 

### Paste a link to your repository here

https://github.com/jpineda48/Concentration-Game
