### ISSUE TITLE
Extra line showing below grid using CSS

### ISSUE THREAD

**Issue by bmaiden** [sei-ec-remote/project-1-issues#191]
### What's the problem you're trying to solve?
Remove extra line at bottom of grid.

### Post any code you think might be relevant (one fenced block per file)
```CSS
#board {
    display: grid;
    grid-template-columns: repeat(4, 15vmin);
    grid-template-rows: repeat(4, 15vmin);
    margin-top: 1vmin;
    gap: 1vmin;
}

.squares {
    display: flex;
    border: 0.3vmin solid black;
    cursor: pointer;
    justify-content: center;
    align-items: center;
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
<img width="577" alt="image" src="https://github.com/sei-ec-remote/project-1-issues/assets/148794472/d2c595ab-1c97-431c-b090-fa4a841f603d">

### What is your best guess as to the source of the problem?
not sure

### What things have you already tried to solve the problem?
changing border aspects in CSS

### Paste a link to your repository here
https://github.com/bmaiden/memory-browser-game
