### ISSUE TITLE
couldn't center the play again button

### ISSUE THREAD

**Issue by FartuunH** [sei-ec-remote/project-1-issues#192]
### What's the problem you're trying to solve?
i wanted to center the play button but its not moving at all

### Post any code you think might be relevant (one fenced block per file)
``` css
button{
    color: beige;
    background-color: var(--clr-4);
    display: flex;
    align-content: center;
    place-content: center;
    letter-spacing: 1.5vmin;
    font-size: 5vmin;
    border-color: #209085 transparent transparent;
    border-style: solid;
    border-radius: 5rem;
}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
the button is on the corner i want it to be center

### What is your best guess as to the source of the problem?
i don't know 

### What things have you already tried to solve the problem?
align-items center
display:flex ;
justify-self: center;

### Paste a link to your repository here
https://github.com/FartuunH/Wordle
