### ISSUE TITLE
Duplicating divs to render game board

### ISSUE THREAD

**Issue by RyanCLuis** [sei-ec-remote/project-1-issues#199]
### What's the problem you're trying to solve?
when i wrote my function to populate my tiles on my board, it makes my divs as i wanted, but for some reason it doesnt fit my board, and i have no idea how to fix it.

### Post any code you think might be relevant (one fenced block per file)
```js
function renderBoard() {
    document.getElementById("mind-count").innerText = minds
    // populate my tiles using a for loop
    for (let r = 0;r < rows; r++) {
        let row = []
        for (let c = 0; c < columns; c++) {
            // making a div tag in HTML
            let tile = document.createElement("div")
            tile.id = `${r}-${c}`
            document.getElementById("tiles").append(tile)
            row.push(tile)
        }
        board.push(row)
    }
    console.log(board)
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
there is no error message but here is what it looks like 
![Capture](https://github.com/sei-ec-remote/project-1-issues/assets/150068816/8eb92cbe-b373-49ca-b708-6f48b210351d)

### What is your best guess as to the source of the problem?
i think it might have to do with my css or maybe my stated variable.

### What things have you already tried to solve the problem?
i tried messing around my state var by changing how many rows and how many columns but it doesn't like to fill the board

### Paste a link to your repository here
https://github.com/RyanCLuis/Minesweeper

**Comment by timmshinbone** [comment]
Share the css that's styling the board

**Comment by RyanCLuis** [comment]
```css
#tiles {
    height: 400px;
    width: 400px;
    border: 10px solid black;
    background-color: lightblue;
    margin: 0 auto;
    display: flex;
    flex-wrap: wrap;
    cursor: crosshair;
}

/* added a div to see what my boxes would look like */
/* simple math, if you are trying to get the width and height of the boxes its 400 divided by 8 to get 50px. But you need to include the boarder which is 0.5px around */
#tiles div {
    width: 48px;
    height: 48px;
    border: 1px solid rgb(158, 77, 7);

    /* adding text style when you reveal the box */
    font-size: 30px;
    display: flex;
    justify-content: center;
    align-items: center;
}
```
