### ISSUE TITLE
Full canvas window shifting up when game ends

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/project-1-issues#33]
### What's the problem you're trying to solve?

When the game ends and returns a h1 message the whole canvas shifts up.

### Post any code you think might be relevant (one fenced block per file)
```css
#container {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}

#stars-counter {
    text-align: right;
    right: 5px;
    top: 520px;
    position: relative;
    z-index: 1;
}

h1 {
    margin: 0;
    text-align: center;
    z-index: 1;
}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

The h1 message should display without shifting the whole canvas up

### What is your best guess as to the source of the problem?

It could be the way I styled the parent div element? I'm not sure.

### What things have you already tried to solve the problem?

I tried changing around things and messing with the numbers in css.

### Paste a link to your repository here

https://github.com/ivycle94/Project-1
